### ISSUE TITLE
Semver breakage

### ISSUE THREAD

**Issue by jcornaz** [onurzdg/mio-misc#11]
Hi, 

It looks like `mio` is a public dependency of `mio-misc`. Which means [bumping to `0.8`](https://github.com/onurzdg/mio-misc/commit/7741fc2a6c858a9b3fb509b3ab7353bbfce13330) was a breaking change, but has been released as part of the `1.3.2` patch.

This resulted in breakage in other projects. For example [bevy](https://github.com/bevyengine/bevy) (on linux): 

```
git clone https://github.com/bevyengine/bevy.git
cd bevy
git checkout 2abf5cc618957ed6a2acf6a496c0039513746cae
cargo update
cargo check --workspace # <-- Compilation error due to semver incompatibility
```

Could you yank `1.3.2` and release your changes as `2.0.0` instead?

**Comment by onurzdg** [comment]
Will do

**Comment by onurzdg** [comment]
Took care of it. Sorry for the inconvenience. Thank you for bringing this to my attention!

**Comment by jcornaz** [comment]
Thanks to you @onurzdg :+1:
